name: tailwind_breakpoints
description: "TailwindCSS style, mobile-first responsive breakpoints for Flutter, with simple getters like context.sm context.md, and more."
version: 0.1.1
repository: https://github.com/sardaar-niamotullah/tailwind_breakpoints
issue_tracker: https://github.com/sardaar-niamotullah/tailwind_breakpoints/issues
homepage: https://github.com/sardaar-niamotullah/tailwind_breakpoints
topics: [responsive, breakpoints, tailwindcss, layout, adaptive]

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
